### ISSUE TITLE
Query not working as documented in README

### ISSUE THREAD

**Issue by CristianCantoro** [dottorblaster/stocazzo#10]
README reads:

### /:query
Will return a JSON-form response with your query as a question and "stocazzo" as the answer.

But query is working with the following syntax:
```
/?q=query
```

Example;
http://stocazzo.io/?q=chi%20%C3%A8%20stato
([source](https://www.youtube.com/watch?v=PLS-mBeeN8U))

**Comment by dottorblaster** [comment]
Have to refactor the docset, this API changed so much since I started implementing :)

**Comment by dottorblaster** [comment]
Better readme as of 0a3d57ba1d89f17a2143e0f27a8a461a0cd34574, closing :)
