### ISSUE TITLE
Using path parameter and configuration setting

### ISSUE THREAD

**Issue by enrichman** [dottorblaster/stocazzo#13]
To add flexibility to the service I propose to use a unique path accepting a parameter, and then determine the correct response thanks to the config object.

Something like:
```
config = {
    caps:
    {
        value: "STOCAZZO",
        big: "GRAN",
        bigger: "GRANDISSIMO"
    }
}
```

and the api
```
server.route({
	method: 'GET',
	path: '/:format',
	handler: function(request, reply) {
		var format = req.params.format;
		var sc = config[format];
		var r = { response: sc.value };

		Utils.requestFormatter(request, r).dilate(request, r, sc.big);
		return reply(JSON.stringify(r)).type('application/json');
	}
});
```

**Comment by dottorblaster** [comment]
Maybe it's time to refactor some stuff and you are right :+1: 

I'm assignin it to 1.3 because it seems compatible with the current syntax

**Comment by dottorblaster** [comment]
@enrichman Implemented :+1: thanks for the feedback! And let me know if you'd make any further change :-)
