### ISSUE TITLE
Please add support for plural to return "sticazzi" as response

### ISSUE THREAD

**Issue by rmarchet** [dottorblaster/stocazzo#21]

**Comment by stefanofrigerio** [comment]
I don't think that this feature should be implemented. 'Sticazzi' means 'I couldn't care less'.

**Comment by dottorblaster** [comment]
@stefanofrigerio I think it as well. Maybe I should close this but I wanna wait some argumentations :)

**Comment by rmarchet** [comment]
Great! I agree with your explanation too, so I close the issue.
