### ISSUE TITLE
add support for STOGRANCAZZO with parameter ?big=1

### ISSUE THREAD

**Issue by lmammino** [dottorblaster/stocazzo#6]

**Comment by dottorblaster** [comment]
Definitely should.

**Comment by mfyameen** [comment]
#upvote

**Comment by dottorblaster** [comment]
![snapshot7](https://cloud.githubusercontent.com/assets/20770/9120785/a1871fe8-3c7e-11e5-951b-e09167a6c2b5.png)

winter is coming

**Comment by lmammino** [comment]
You (and `gandalf`) are great!

**Comment by dottorblaster** [comment]
As of @cbcb4ff89408da347a1f2d1d18ebd456c7705c84 this is implemented. I won't close this until I have rewritten the docs. :)

**Comment by dottorblaster** [comment]
Changed my mind :D closing as the docset bug is filed in #10
